### ISSUE TITLE
FileNotFoundError: annotations/full/rec_fpv_segments_indices.p

### ISSUE THREAD

**Issue by idejie** [Buzz-Beater/LEMMA#3]
When I run the TPV recognition with the command `python rec_main.py --cfg settings/slowfast_tpv_plain_hoi.yaml EXP.MODEL_TYPE branch EXP.VIEW_TYPE tpv`, got an error:

```
-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/home/yangdejie/anaconda3/envs/SlowFast/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
  File "/home/yangdejie/projects/LEMMA/utils/model_utils/multiprocessing.py", line 50, in run
    func(cfg)
  File "/home/yangdejie/projects/LEMMA/utils/exp_utils/recognition.py", line 280, in train
    train_loader = loader.construct_loader(cfg, 'train')
  File "/home/yangdejie/projects/LEMMA/datasets/loader.py", line 97, in construct_loader
    dataset = build_dataset(dataset_name, cfg, split, subclass=subclass)
  File "/home/yangdejie/projects/LEMMA/datasets/build.py", line 31, in build_dataset
    return DATASET_REGISTRY.get(name)(cfg, split, subclass)
  File "/home/yangdejie/projects/LEMMA/datasets/seg_dataset.py", line 68, in __init__
    self._load_data(verbose=cfg.DEBUG)
  File "/home/yangdejie/projects/LEMMA/datasets/seg_dataset.py", line 122, in _load_data
    anno_rel_path, split_file=split_file)
  File "/home/yangdejie/projects/LEMMA/datasets/utils.py", line 126, in get_selected_indices
    ).open('rb') as f:
  File "/home/yangdejie/anaconda3/envs/SlowFast/lib/python3.7/pathlib.py", line 1208, in open
    opener=self._opener)
  File "/home/yangdejie/anaconda3/envs/SlowFast/lib/python3.7/pathlib.py", line 1063, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/home/yangdejie/data2/lemma/annotations/full/rec_fpv_segments_indices.p'
```

How can I get this file?

Thank you very much.

**Comment by Buzz-Beater** [comment]
I have added these files into the dataset folder, they are basically segment boundaries in the untrimmed video following the form:
```
[
...
(vid_id, start_frame, length)
...
]
```
You might as well generate this on your own given the per-frame annotation.

**Comment by idejie** [comment]
Thanks for your reply and answer!
