### ISSUE TITLE
ERROR: Got NaN losses 2021-10-28 23:20:46.797813

### ISSUE THREAD

**Issue by wqtwjt1996** [Buzz-Beater/LEMMA#5]
Traceback (most recent call last):
  File "rec_main.py", line 167, in <module>
    main()
  File "rec_main.py", line 160, in main
    train(cfg=cfg)
  File "/usa/wqtwjt/LEMMA/utils/exp_utils/recognition.py", line 302, in train
    train_epoch(train_loader, model, optimizer, train_meter, cur_epoch, cfg)
  File "/usa/wqtwjt/LEMMA/utils/exp_utils/recognition.py", line 89, in train_epoch
    misc.check_nan_losses(loss)
  File "/usa/wqtwjt/LEMMA/utils/model_utils/misc.py", line 27, in check_nan_losses
    raise RuntimeError("ERROR: Got NaN losses {}".format(datetime.now()))
RuntimeError: ERROR: Got NaN losses 2021-10-28 23:20:46.797813

**Comment by Buzz-Beater** [comment]
Hi, sorry for the late reply, are you running experiments with the provided configuration file?
